# Generated by Django 5.2.8 on 2025-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='fullness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='start_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='paused', max_length=20),
        ),
    ]
