# Generated by Django 5.2.8 on 2025-11-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_queue_fullness_alter_queue_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.queue'),
        ),
    ]
